### ISSUE TITLE
airbook m2 無法開啟FFXIVChnTextPatch-GP

### ISSUE THREAD

**Issue by RiceeeChang** [hydai/FFXIVChnTextPatch-GP#11]
掛載後雙擊應用程式之後毫無反應，我也把安全性改成允許任何來源了，一樣沒有反應

**Comment by hydai** [comment]
他是完全沒有被啟動嗎？還是啟動後馬上結束？

**Comment by RiceeeChang** [comment]
我不確定是不是啟動後馬上結束 至少我肉眼是沒有看到任何啟動的痕跡的

**Comment by hydai** [comment]
那你試試看從 terminal 裡面執行 .app 檔案看有沒有印出什麼 log

**Comment by hydai** [comment]
我剛才在 m2 max 上面測試可以執行，沒辦法重現這個問題

**Comment by RiceeeChang** [comment]
後來發現是權限不足...

**Comment by hydai** [comment]
好喔XD
